before_script:
- nuget restore Leaf/Leaf.sln

linux-build:
  stage: build
  image: mono
  script:
  - xbuild /p:Configuration=Release Leaf/Leaf/Leaf.csproj
  artifacts:
    paths:
    - Leaf/Leaf/bin/Release/

linux-test:
  stage: test
  image: mono
  script:
  - xbuild /p:Configuration=Release Leaf/Leaf.Tests/Leaf.Tests.csproj
  - mono Leaf/packages/NUnit.ConsoleRunner.3.4.1/tools/nunit3-console.exe Leaf/Leaf.Tests/bin/Release/Leaf.Tests.dll
  artifacts:
    paths:
    - Leaf/Leaf.Tests/bin/Release/
